package org.picomatrix.bridge.protocol;

// Generated by scripts/contracts.py; do not edit tags by hand.
public final class MatrixContract {
    public static final String SOURCE_SHA256 = "e3526ead6143f86b6635f14d1ece8af7211bde2552e883faafec717e129b35d8";
    public static final class Request {
        public static final int cmd = 1;
        public static final int sequenceId = 2;
        public static final int sdkVersion = 3;
        public static final int appKey = 4;
        public static final int deviceId = 5;
        public static final int channel = 6;
        public static final int appVersionCode = 7;
        public static final int extraParams = 9;
        public static final int appPkg = 10;
        public static final int body = 11;
        public static final int accessToken = 12;
        public static final int monitorInfo = 13;
        public static final int originCallerAppPkg = 14;
    }
    public static final class Response {
        public static final int cmd = 1;
        public static final int statusCode = 2;
        public static final int errorMsg = 3;
        public static final int logId = 4;
        public static final int sequenceId = 6;
        public static final int body = 7;
        public static final int accessToken = 8;
        public static final int monitorInfo = 9;
        public static final int extraParams = 10;
    }
    public static final class GetConfigurationRequest {
        public static final int modules = 1;
        public static final int appId = 2;
        public static final int accessToken = 3;
    }
    public static final class GetConfigurationResponse {
        public static final int configurations = 1;
    }
    public static final class GetTTNetParametersResponse {
        public static final int parameters = 1;
    }
    public static final class GetAccessInfoSilenceResponse {
        public static final int accessToken = 4;
        public static final int openUid = 5;
    }
    public static final class GetAccessTokenRequest {
        public static final int skipLoginPage = 1;
        public static final int forceNeedScopes = 2;
    }
    public static final class GetAccessTokenResponse {
        public static final int accessToken = 1;
        public static final int authorizedScopes = 2;
    }
    public static final class GetCurrentOpenUserInfoResponse {
        public static final int loginUser = 1;
    }
    public static final class OpenUserInfo {
        public static final int openUid = 1;
        public static final int accessToken = 2;
        public static final int displayName = 3;
        public static final int avatarUrl = 4;
        public static final int accountId = 5;
        public static final int picoId = 6;
        public static final int gender = 7;
        public static final int introduction = 8;
        public static final int status = 9;
        public static final int lastOnline = 10;
        public static final int fromAppId = 11;
        public static final int presenceName = 12;
        public static final int presenceDeepLinkMsg = 13;
        public static final int presenceDestinationApi = 14;
        public static final int presenceLobbySession = 15;
        public static final int presenceMatchSession = 16;
        public static final int presenceStatus = 17;
        public static final int presencePackage = 18;
        public static final int inviteToken = 19;
        public static final int smallImageUrl = 20;
        public static final int presenceExtra = 21;
        public static final int storeRegion = 22;
        public static final int secUid = 23;
        public static final int presenceIsJoinable = 24;
    }
    public static final int CMD_CONFIGURATION_GET_CONFIGURATION = 20100;
    public static final int CMD_GET_TTNET_PARAMETERS = 200000002;
    public static final int CMD_GET_ACCESS_INFO_SILENCE = 10012;
    public static final int CMD_GET_OPEN_USER_INFO = 10001;
    public static final int CMD_GET_OPEN_ACCESS_TOKEN = 10002;
    public static final int RequestBody_getConfigurationRequest = 20100;
    public static final int ResponseBody_getConfigurationResponse = 20100;
    public static final int ResponseBody_getTTNetParametersResponse = 200000002;
    public static final int RequestBody_getAccessInfoSilenceRequest = 10012;
    public static final int ResponseBody_getAccessInfoSilenceResponse = 10012;
    public static final int RequestBody_getCurrentOpenUserInfoRequest = 10002;
    public static final int ResponseBody_getCurrentOpenUserInfoResponse = 10002;
    public static final int RequestBody_getAccessTokenRequest = 10001;
    public static final int ResponseBody_getAccessTokenResponse = 10001;
}
