#!/usr/bin/env python3
"""Derive stable interface data and runtime constants from a direct DEX inspection."""
import argparse
import hashlib
import json
from pathlib import Path
import re

PREFIX = "Lcom/bytedance/pico/matrix/proto/"
SELECTED = ("Request", "Response", "GetConfigurationRequest", "GetConfigurationResponse", "GetTTNetParametersResponse",
            "GetAccessInfoSilenceResponse", "GetAccessTokenRequest", "GetAccessTokenResponse",
            "GetCurrentOpenUserInfoResponse", "OpenUserInfo")

def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()

def profile(inspection):
    contracts = inspection["contracts"]
    if not contracts["commands"] or not contracts["messages"]:
        raise ValueError("input contains no Matrix contracts")
    return {"schemaVersion": 1, "source": inspection["source"],
            "package": inspection["manifest"]["package"],
            "versionCode": inspection["manifest"]["versionCode"],
            "contractSha256": hashlib.sha256(canonical(contracts)).hexdigest(),
            "contracts": contracts, "entrypoints": inspection.get("entrypoints", {}),
            "libraries": inspection["matrix"].get("libraries", [])}

def compare(old, new):
    changes=[]
    a,b=old["contracts"],new["contracts"]
    for kind in ("commands", "messages"):
        for name in sorted(set(a[kind]) | set(b[kind])):
            if a[kind].get(name) != b[kind].get(name):
                changes.append({"kind": kind, "name": name, "before": a[kind].get(name), "after": b[kind].get(name)})
    if old.get("entrypoints") != new.get("entrypoints"):
        changes.append({"kind":"entrypoints", "before":old.get("entrypoints"), "after":new.get("entrypoints")})
    return {"schemaVersion":1, "oldSourceSha256":old["source"]["sha256"], "newSourceSha256":new["source"]["sha256"],
            "declarationsEqual":not changes, "changes":changes,
            "nativeLibrariesEqual":old.get("libraries")==new.get("libraries"),
            "requiresDeviceValidation":old["source"]["sha256"]!=new["source"]["sha256"]}

def generate_java(p):
    lines=["package org.picomatrix.bridge.protocol;", "", "// Generated by scripts/contracts.py; do not edit tags by hand.",
           "public final class MatrixContract {", f'    public static final String SOURCE_SHA256 = "{p["source"]["sha256"]}";']
    for name in SELECTED:
        fields=p["contracts"]["messages"][PREFIX+name+";"]
        lines.append(f"    public static final class {name} {{")
        for field in fields:
            if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", field["name"]): raise ValueError("invalid field name")
            lines.append(f'        public static final int {field["name"]} = {field["tag"]};')
        lines.append("    }")
    for name in ("CMD_CONFIGURATION_GET_CONFIGURATION", "CMD_GET_TTNET_PARAMETERS", "CMD_GET_ACCESS_INFO_SILENCE", "CMD_GET_OPEN_USER_INFO", "CMD_GET_OPEN_ACCESS_TOKEN"):
        lines.append(f'    public static final int {name} = {p["contracts"]["commands"][name]};')
    # Wrapper tags are extracted too; they must not be inferred from command IDs.
    wrappers = [("RequestBody","getConfigurationRequest"),("ResponseBody","getConfigurationResponse"),("ResponseBody","getTTNetParametersResponse")]
    for stem in ("getAccessInfoSilence", "getCurrentOpenUserInfo", "getAccessToken"):
        wrappers.extend((("RequestBody", stem+"Request"), ("ResponseBody", stem+"Response")))
    for message, field in wrappers:
        tag=next(f["tag"] for f in p["contracts"]["messages"][PREFIX+message+";"] if f["name"]==field)
        lines.append(f'    public static final int {message}_{field} = {tag};')
    return "\n".join(lines+["}",""])

def main():
    parser=argparse.ArgumentParser(); sub=parser.add_subparsers(dest="command",required=True)
    create=sub.add_parser("extract");create.add_argument("inspection",type=Path);create.add_argument("output",type=Path);create.add_argument("--java",type=Path)
    diff=sub.add_parser("diff");diff.add_argument("old",type=Path);diff.add_argument("new",type=Path);diff.add_argument("output",type=Path)
    args=parser.parse_args()
    if args.command=="extract":
        value=profile(json.loads(args.inspection.read_text()))
        if args.java:
            args.java.parent.mkdir(parents=True,exist_ok=True);args.java.write_text(generate_java(value))
    else: value=compare(json.loads(args.old.read_text()),json.loads(args.new.read_text()))
    args.output.parent.mkdir(parents=True,exist_ok=True);args.output.write_text(json.dumps(value,sort_keys=True,indent=2,ensure_ascii=False)+"\n")
    print(json.dumps({"output":str(args.output),"command":args.command}))

if __name__=="__main__": main()
